name = "demo-pi-pico-2"
target = "thumbv8m.main-none-eabihf"
chip = "../../chips/rp235x"
board = "pi-pico-2"
memory = "memory-pico-2.toml"
stacksize = 944

[kernel]
name = "demo-pi-pico-2"
requires = {flash = 20000, ram = 1312}
stacksize = 640

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 4096, ram = 512}
start = true
stacksize = 352
notifications = ["fault", "timer"]

[tasks.blinky]
name = "task-blinky"
priority = 1
max-sizes = {flash = 8192, ram = 2048}
stacksize = 128
uses = ["sio", "io_bank0", "pads_bank0"]
start = true

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true
