[[flash]]
# SRAM_BASE
address = 0x1000_0000
# 4MB (0x0040_0000)
size = 4194304
read = true
execute = true

[[ram]]
address = 0x2000_0000
# Logically, there is a single 520KB contiguous memory
size = 532480
read = true
write = true
execute = true
